### ISSUE TITLE
the U1 name?

### ISSUE THREAD

**Issue by hualazimo7** [veremenko-y/famicom-to-nes#1]
I see AVR CIC on the pcb, which chip should I use?
☺

**Comment by veremenko-y** [comment]
IC is ATTiny13, you can find firmware here: https://github.com/krikzz/avrciczz it's avrciczz project. 

FYI I made the boards, but still haven't tested it. On the first iteration, I made 1.6mm pcb, and it was a mistake. Make sure you order 1.2mm.

1.6 is too thick for NES ZIF socket.

**Comment by veremenko-y** [comment]
Updated README.md as well.

**Comment by hualazimo7** [comment]
> IC is ATTiny13, you can find firmware here: https://githubfast.com/krikzz/avrciczz it's avrciczz project.
> 
> FYI I made the boards, but still haven't tested it. On the first iteration, I made 1.6mm pcb, and it was a mistake. Make sure you order 1.2mm.
> 
> 1.6 is too thick for NES ZIF socket.

1.2mm thickness is perfect.  Test succeeded, thanks.

**Comment by veremenko-y** [comment]
> > IC is ATTiny13, you can find firmware here: https://githubfast.com/krikzz/avrciczz it's avrciczz project.
> > FYI I made the boards, but still haven't tested it. On the first iteration, I made 1.6mm pcb, and it was a mistake. Make sure you order 1.2mm.
> > 1.6 is too thick for NES ZIF socket.
> 
> 1.2mm thickness is perfect. Test succeeded, thanks.

Did you make one and it worked for you?

**Comment by hualazimo7** [comment]
> > > IC is ATTiny13, you can find firmware here: https://githubfast.com/krikzz/avrciczz it's avrciczz project.
> > > FYI I made the boards, but still haven't tested it. On the first iteration, I made 1.6mm pcb, and it was a mistake. Make sure you order 1.2mm.
> > > 1.6 is too thick for NES ZIF socket.
> > 
> > 
> > 1.2mm thickness is perfect. Test succeeded, thanks.
> 
> Did you make one and it worked for you?

Yes, It worked on my Retroad console, a third-party product,  just like NES. 
the console needs resetting  6-8 times indeed.
